version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      # Add database connection environment variables
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: krishav
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: postgres
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: krishav
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
